// Generated by Claude

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:sqflite/sqflite.dart';
import 'package:connectivity_plus/connectivity_plus.dart';

Map<String, dynamic> _normalizeForSqlite(Map<String, dynamic> data) {
  final normalized = <String, dynamic>{};

  for (final entry in data.entries) {
    final value = entry.value;

    if (value is Timestamp) {
      normalized[entry.key] = value.toDate().toIso8601String();
    } else if (value is DateTime) {
      normalized[entry.key] = value.toIso8601String();
    } else if (value is Map) {
      normalized[entry.key] = _normalizeForSqlite(
        Map<String, dynamic>.from(value),
      );
    } else if (value is List) {
      normalized[entry.key] = value.map((item) {
        if (item is Timestamp) {
          return item.toDate().toIso8601String();
        }
        if (item is DateTime) {
          return item.toIso8601String();
        }
        if (item is Map) {
          return _normalizeForSqlite(Map<String, dynamic>.from(item));
        }
        return item;
      }).toList();
    } else {
      normalized[entry.key] = value;
    }
  }

  return normalized;
}

class SyncService {
  final Database localDb;
  final FirebaseFirestore firestore;

  SyncService({required this.localDb, FirebaseFirestore? firestore})
    : firestore = firestore ?? FirebaseFirestore.instance;

  Map<String, dynamic> _sanitizeForTable({
    required String tableName,
    required Map<String, dynamic> data,
  }) {
    final normalized = _normalizeForSqlite(data);
    final allowedColumns = <String>{};

    if (tableName == 'users') {
      allowedColumns.addAll({
        'id',
        'name',
        'email',
        'password',
        'role',
        'classCode',
        'synced',
      });
    } else if (tableName == 'attempts') {
      allowedColumns.addAll({
        'id',
        'uid',
        'wordText',
        'listId',
        'score',
        'feedback',
        'createdAt',
        'durationMs',
        'recordingPath',
        'synced',
      });
    } else if (tableName == 'currentList') {
      allowedColumns.addAll({
        'id',
        'uid',
        'currentListId',
        'synced',
      });
    }

    return Map.fromEntries(
      normalized.entries.where((entry) => allowedColumns.contains(entry.key)),
    );
  }

  // Check if online
  Future<bool> isOnline() async {
    final result = await Connectivity().checkConnectivity();
    return result.isNotEmpty;
  }

  // Push local changes to cloud
  Future<void> pushToCloud({
    required String tableName,
    required String primaryKey,
  }) async {
    if (!await isOnline()) return;

    try {
      // Get unsynced items
      final items = await localDb.query(
        tableName,
        where: 'synced = ?',
        whereArgs: [0],
      );

      for (var item in items) {
        final itemToSync = Map<String, dynamic>.from(item);
        itemToSync.remove('synced'); // Remove local-only field

        try {
          final docId = item[primaryKey].toString();
          await firestore.collection(tableName).doc(docId).set(
            itemToSync,
            SetOptions(merge: true),
          );

          // Mark as synced
          await localDb.update(
            tableName,
            {'synced': 1},
            where: '$primaryKey = ?',
            whereArgs: [item[primaryKey]],
          );
        } catch (e) {
          print('Failed to sync item: $e');
        }
      }
    } catch (e) {
      print('Push failed: $e');
    }
  }

  // Pull cloud changes to local
  Future<void> pullFromCloud({
    required String tableName,
    required String primaryKey,
  }) async {
    if (!await isOnline()) return;

    try {
      final snapshot = await firestore.collection(tableName).get();

      for (var doc in snapshot.docs) {
        final firestoreId = doc.id;
        final idValue = int.tryParse(firestoreId);
        final localId = idValue ?? 0;

        // Check if exists locally
        final existing = await localDb.query(
          tableName,
          where: '$primaryKey = ?',
          whereArgs: [localId],
        );

        final itemToInsert = _sanitizeForTable(
          tableName: tableName,
          data: Map<String, dynamic>.from(doc.data()),
        );
        if (itemToInsert.containsKey(primaryKey)) {
          itemToInsert[primaryKey] = localId;
        }
        itemToInsert['synced'] = 1;

        if (existing.isEmpty && localId == 0) {
          continue;
        }

        if (existing.isEmpty) {
          // New item from cloud
          await localDb.insert(tableName, itemToInsert);
        } else {
          await localDb.update(
            tableName,
            itemToInsert,
            where: '$primaryKey = ?',
            whereArgs: [localId],
          );
        }
      }
    } catch (e) {
      print('Pull failed: $e');
    }
  }

  // Full bidirectional sync
  Future<void> fullSync({
    required String tableName,
    required String primaryKey,
  }) async {
    if (!await isOnline()) return;

    await pushToCloud(tableName: tableName, primaryKey: primaryKey);
    await pullFromCloud(tableName: tableName, primaryKey: primaryKey);
  }

  // Sync multiple tables
  Future<void> syncMultipleTables(List<SyncTableConfig> configs) async {
    for (var config in configs) {
      await fullSync(
        tableName: config.tableName,
        primaryKey: config.primaryKey,
      );
    }
  }

  // Delete from both local and cloud
  Future<void> deleteEverywhere({
    required String tableName,
    required String primaryKey,
    required dynamic id,
  }) async {
    await localDb.delete(tableName, where: '$primaryKey = ?', whereArgs: [id]);

    if (await isOnline()) {
      try {
        await firestore.collection(tableName).doc(id.toString()).delete();
      } catch (e) {
        print('Cloud deletion failed: $e');
      }
    }
  }
}

class SyncTableConfig {
  final String tableName;
  final String primaryKey;

  SyncTableConfig({required this.tableName, required this.primaryKey});
}
