// Generated by Claude

import 'package:sqflite/sqflite.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:connectivity_plus/connectivity_plus.dart';

class SyncService {
  final Database localDb;
  final SupabaseClient supabase;

  SyncService({required this.localDb, required this.supabase});

  // Check if online
  Future<bool> isOnline() async {
    final result = await Connectivity().checkConnectivity();
    return result.isNotEmpty;
  }

  // Push local changes to cloud
  Future<void> pushToCloud({
    required String tableName,
    required String primaryKey,
  }) async {
    if (!await isOnline()) return;

    try {
      // Get unsynced items
      final items = await localDb.query(
        tableName,
        where: 'synced = ?',
        whereArgs: [0],
      );

      for (var item in items) {
        final itemToSync = Map<String, dynamic>.from(item);
        itemToSync.remove('synced'); // Remove local-only field

        try {
          await supabase.from(tableName).upsert(itemToSync);

          // Mark as synced
          await localDb.update(
            tableName,
            {'synced': 1},
            where: '$primaryKey = ?',
            whereArgs: [item[primaryKey]],
          );
        } catch (e) {
          print('Failed to sync item: $e');
        }
      }
    } catch (e) {
      print('Push failed: $e');
    }
  }

  // Pull cloud changes to local
  Future<void> pullFromCloud({
    required String tableName,
    required String primaryKey,
  }) async {
    if (!await isOnline()) return;

    try {
      final cloudItems = await supabase.from(tableName).select();

      for (var cloudItem in cloudItems) {
        final id = cloudItem[primaryKey];

        // Check if exists locally
        final existing = await localDb.query(
          tableName,
          where: '$primaryKey = ?',
          whereArgs: [id],
        );

        final itemToInsert = Map<String, dynamic>.from(cloudItem);
        itemToInsert['synced'] = 1;

        if (existing.isEmpty) {
          // New item from cloud
          await localDb.insert(tableName, itemToInsert);
        } else {
          await localDb.update(
            tableName,
            itemToInsert,
            where: '$primaryKey = ?',
            whereArgs: [id],
          );
        }
      }
    } catch (e) {
      print('Pull failed: $e');
    }
  }

  // Full bidirectional sync
  Future<void> fullSync({
    required String tableName,
    required String primaryKey,
  }) async {
    if (!await isOnline()) return;

    await pushToCloud(tableName: tableName, primaryKey: primaryKey);
    await pullFromCloud(tableName: tableName, primaryKey: primaryKey);
  }

  // Sync multiple tables
  Future<void> syncMultipleTables(List<SyncTableConfig> configs) async {
    for (var config in configs) {
      await fullSync(
        tableName: config.tableName,
        primaryKey: config.primaryKey,
      );
    }
  }

  // Delete from both local and cloud
  Future<void> deleteEverywhere({
    required String tableName,
    required String primaryKey,
    required dynamic id,
  }) async {
    await localDb.delete(tableName, where: '$primaryKey = ?', whereArgs: [id]);

    if (await isOnline()) {
      try {
        await supabase.from(tableName).delete().eq(primaryKey, id);
      } catch (e) {
        print('Cloud deletion failed: $e');
      }
    }
  }
}

class SyncTableConfig {
  final String tableName;
  final String primaryKey;

  SyncTableConfig({required this.tableName, required this.primaryKey});
}
